name: My First WorkFlow

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5

      - name: Create application.properties
        run: |
          mkdir -p src/main/resources
          echo "spring.application.name=replay" > src/main/resources/application.properties
          echo "spring.datasource.url=${{ secrets.DB_URL }}" >> src/main/resources/application.properties
          echo "spring.datasource.username=${{ secrets.DB_USERNAME }}" >> src/main/resources/application.properties
          echo "spring.datasource.password=${{ secrets.DB_PASSWORD }}" >> src/main/resources/application.properties
          echo "spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver" >> src/main/resources/application.properties
          echo "spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect" >> src/main/resources/application.properties
          echo "spring.jpa.hibernate.ddl-auto=update" >> src/main/resources/application.properties
          echo "spring.jpa.properties.hibernate.format_sql=true" >> src/main/resources/application.properties
          echo "application.security.jwt.secret-key=${{ secrets.JWT_SECRET_KEY }}" >> src/main/resources/application.properties
          echo "application.security.jwt.expiration=2592000000" >> src/main/resources/application.properties
          echo "aws.accessKeyId=${{ secrets.AWS_ACCESS_KEY_ID }}" >> src/main/resources/application.properties
          echo "aws.secretKey=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> src/main/resources/application.properties
          echo "aws.region=ap-northeast-2" >> src/main/resources/application.properties
          echo "aws.s3.bucket=${{ secrets.S3_BUCKET_NAME }}" >> src/main/resources/application.properties
          echo "cloud.aws.region.static=ap-northeast-2" >> src/main/resources/application.properties
          echo "cloud.aws.credentials.accessKey=${{ secrets.AWS_ACCESS_KEY_ID }}" >> src/main/resources/application.properties
          echo "cloud.aws.credentials.secretKey=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> src/main/resources/application.properties
          echo "cloud.aws.s3.bucket=${{ secrets.S3_BUCKET_NAME }}" >> src/main/resources/application.properties
          echo "spring.servlet.multipart.enabled=true" >> src/main/resources/application.properties
          echo "spring.servlet.multipart.max-file-size=10MB" >> src/main/resources/application.properties
          echo "spring.servlet.multipart.max-request-size=10MB" >> src/main/resources/application.properties
          echo "logging.level.org.springframework.security=DEBUG" >> src/main/resources/application.properties
          echo "spring.mail.host=smtp.gmail.com" >> src/main/resources/application.properties
          echo "spring.mail.port=587" >> src/main/resources/application.properties
          echo "spring.mail.username=${{ secrets.GMAIL_USERNAME }}" >> src/main/resources/application.properties
          echo "spring.mail.password=${{ secrets.GMAIL_PASSWORD }}" >> src/main/resources/application.properties
          echo "spring.mail.properties.mail.smtp.starttls.enable=true" >> src/main/resources/application.properties
          echo "spring.mail.properties.mail.smtp.auth=true" >> src/main/resources/application.properties
          cat src/main/resources/application.properties # 확인을 위해 출력

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Clean and build with Gradle
        run: ./gradlew clean build --no-daemon --stacktrace

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1.3.3

      - name: Build and push Docker image
        env:
          ECR_REGISTRY: 975050003330.dkr.ecr.ap-northeast-2.amazonaws.com
          ECR_REPOSITORY: replay
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to EC2
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          ECR_REGISTRY: 975050003330.dkr.ecr.ap-northeast-2.amazonaws.com
          ECR_REPOSITORY: replay
          IMAGE_TAG: ${{ github.sha }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_HOST: ${{ secrets.EC2_PUBLIC_IP }}
        run: |
          echo "$SSH_PRIVATE_KEY" > private_key.pem
          chmod 400 private_key.pem
          ssh -o StrictHostKeyChecking=no -i private_key.pem ubuntu@$SSH_HOST << 'EOF'
            sudo docker system prune -a -f
            aws ecr get-login-password --region ap-northeast-2 | sudo docker login --username AWS --password-stdin 975050003330.dkr.ecr.ap-northeast-2.amazonaws.com
            sudo docker pull 975050003330.dkr.ecr.ap-northeast-2.amazonaws.com/replay:${{ github.sha }}
            sudo docker stop replay || true
            sudo docker rm replay || true
            sudo docker run -d --name replay -p 8080:8080 975050003330.dkr.ecr.ap-northeast-2.amazonaws.com/replay:${{ github.sha }}
            sudo docker logs replay
            sudo docker ps -a
            sudo docker inspect replay
          EOF

  dependency-submission:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Generate and submit dependency graph
        uses: gradle/actions/dependency-submission@417ae3ccd767c252f5661f1ace9f835f9654f2b5